In [1]:
from keras.models import Sequential
from keras.layers.core import Dense
from keras.utils import np_utils
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

import pandas as pd
import seaborn as sns
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline

import numpy as np
import tensorflow as tf
import seaborn as sns

mpl.rcParams['axes.unicode_minus'] = False
plt.rcParams["font.family"] = 'Malgun Gothic'
plt.rcParams["font.size"] = 10


Using TensorFlow backend.


In [2]:
# 1. 다음과 같은 어레이를 Numpy를 이용하여 만드시오
# 1)
a = np.arange(0,5,0.5)
# 2)
b = np.arange(1,11).reshape((2,5))
# 3)
c = np.zeros((3,3))
# 4)
d = np.ones((4,4))

# 5)
e = np.arange(1,25,2).reshape(3,4)

In [4]:
print(a)
print(b)
print(c)
print(d)
print(e)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]]


In [6]:
# 2. 다음과 같은 데이터 프레임을 만드시오

data = {
    "2015": [9904312, 3448737, 2890451, 2466052],
    "2010": [9631482, 3393191, 2632035, 2431774],
    "2005": [9762546, 3512547, 2517680, 2456016],
    "2000": [9853972, 3655437, 2466338, 2473990],
    "지역": ["수도권", "경상권", "수도권", "경상권"]
}
columns = ["지역", "2015", "2010", "2005", "2000"]
index = ["서울", "부산", "인천", "대구"]
df = pd.DataFrame(data, index=index, columns=columns)
df["2010-2015 증가율"] = ((df["2015"] - df["2010"]) / df["2010"]).round(4)
print(df)

     지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0164
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141


In [12]:
# 3. 타이타닉호 슥액에 대해서 다음을 구하시오

# 1) 성별(sex) 인원수, 선실수(class) 인원수, 사망/생존(alive) 인원수를 구하시오
titanic = sns.load_dataset("titanic")
print("성별 인원수",titanic['sex'].value_counts(), sep = '\n')
print(titanic['class'].value_counts())
print(titanic['alive'].value_counts())

성별 인원수
male      577
female    314
Name: sex, dtype: int64
Third     491
First     216
Second    184
Name: class, dtype: int64
no     549
yes    342
Name: alive, dtype: int64
